# Generated by Django 4.0 on 2021-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
