# Generated by Django 4.0 on 2022-01-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
