# Generated by Django 4.0 on 2022-01-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_total_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='price',
        ),
        migrations.AddField(
            model_name='total',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
