# Generated by Django 4.0 on 2022-01-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_total_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
