# Generated by Django 4.0 on 2022-01-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_total_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
