# Generated by Django 4.0 on 2022-01-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_calc_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='old',
            field=models.IntegerField(null=True),
        ),
    ]
