# Generated by Django 4.0 on 2022-01-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_calc_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
