# Generated by Django 4.0 on 2022-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_calc_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='old',
            field=models.FloatField(null=True),
        ),
    ]
