# Generated by Django 4.0 on 2022-01-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_calc_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='old',
        ),
        migrations.AddField(
            model_name='calc',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
