# Generated by Django 4.0 on 2022-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_calc_old_calc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
