# Generated by Django 4.0 on 2022-01-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_calc_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='price',
        ),
    ]
